import time
from selenium.webdriver.common.by import By
from selenium import webdriver
driver = webdriver.Chrome()
time.sleep(1)
driver.get("https://goferjek81.trioangledemo.com")
print("browser redirectign")
driver.maximize_window()
time.sleep(2)
print("values have")
driver.find_element(By.XPATH,"//button[@class='btn sign_btns_bg px-5 py-2']").click()
time.sleep(2)
#driver.find_element(By.XPATH,"//input[@ng-model='user_phone_number']").send_keys("keys.BACKSPACE")
#print("Backspace done")
driver.find_element(By.XPATH,"//button[@class='btn btn-primary mt-3 login_sub_btn']").click()
time.sleep(2)
driver.find_element(By.XPATH,"//button[@id='user_signin_action']").click()
time.sleep(2)
driver.find_element(By.XPATH,"//img[@class='cls_logo']").click()
time.sleep(1)
driver.execute_script("window.scrollTo(0, 400)")
time.sleep(1)
driver.find_element(By.XPATH,"//a[@aria-controls='pills-DeliveryAll']").click()
time.sleep(2)
driver.find_element(By.XPATH,"//a[@href='https://goferjek81.trioangledemo.com/deliveryall/newhome?service_type=1']").click()
time.sleep(1)
driver.find_element(By.XPATH,"//input[@placeholder='Enter Your Delivery Address']").click()
time.sleep(1)
driver.find_element(By.XPATH,"//input[@placeholder='Enter Your Delivery Address']").send_keys("Madurai")
time.sleep(3)
driver.execute_script("window.scrollTo(0,150)")
time.sleep(2)
#driver.find_element(By.XPATH,"//div[@id='google_results']").click
driver.find_element(By.XPATH,"//li[@data_id='ChIJFSAYuGnQADsRF3_75hRYz5A']").click()
#driver.find_element(By.XPATH,"//li[@data_id='ChIJFSAYuGnQADsRF3_75hRYz5A']").click()
time.sleep(1)
driver.find_element(By.XPATH,"//button[@class='cls_submit find_store']").click()
time.sleep(3)
driver.execute_script("window.scrollTo(0,700)")
time.sleep(4)
driver.find_element(By.XPATH,"//a[@data-id='10025']").click()
time.sleep(8)
driver.execute_script("window.scrollTo(0,600)")
time.sleep(5)
driver.find_element(By.XPATH,"//a[@data-value='menu-tab119']").click()
time.sleep(5)
driver.execute_script("window.scrollTo(0,705)")
time.sleep(5)
driver.find_element(By.XPATH,"//div[@data-name=' Veg Noodle Soup']").click()
time.sleep(5)
driver.find_element(By.XPATH,"//a[@data-val='add']").click()
time.sleep(2)
driver.find_element(By.XPATH,"//button[@data-target='#order_modal123']").click()
time.sleep(4)
driver.execute_script("window.scrollTo(0,900)")
time.sleep(3)
driver.find_element(By.XPATH,"//div[@data-id='402']").click()
time.sleep(3)
driver.find_element(By.XPATH,"//a[@data-val='add']").click()
time.sleep(1)
driver.find_element(By.XPATH,"//a[@data-val='add']").click()
time.sleep(3)
#driver.find_element(By.XPATH,"//textarea[@ng-model='add_notes']").send_keys("Need good Food")
#time.sleep(5)
driver.find_element(By.XPATH,"//button[@data-target='#order_modal123']").click()
time.sleep(3)
print ("process stopped in before checkout")
time.sleep(3)
driver.find_element(By.XPATH,"//button[@class='proceed_btn']").click()
time.sleep(3)
driver.find_element(By.XPATH,"//button[@class='place_order_btn']").click()
time.sleep(5)
print("payment page redirection and completed ")
time.sleep(1)




